# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: auth
#   labels:
#     app: auth
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: auth
#   strategy:
#   type: RollingUpdate
#   rollingUpdate:
#     maxSurge: 3
#   template:
#     metadata:
#       labels:
#         app: auth
#     spec:
#       containers:
#         - name: auth
#           image: bazy12/auth
#           ports:
#             - containerPort: 5000
#           envFrom:
#             - configMapRef:
#                 name: auth-config
#               -secretRef:
#                 name: auth-secret


apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  selector:
    matchLabels:
      app: auth
  template:  # Ensure 'template' aligns under 'spec'
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: bazy12/auth
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:   # Fixed the indentation for secretRef
                name: auth-secret
