apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels: 
    app: notification
spec: 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  replicas: 4
  selector:
    matchLabels:
      app: notification
  template: 
    metadata:
      labels:
        app: notification
    spec:
      containers:
       - name: notification
         image: bazy12/notification
         
         envFrom:
           - configMapRef:
               name: notification-configmap
           - secretRef:
              name: notification-secret